<?php

return [
    'access_token' => env('HUBSPOT_ACCESS_TOKEN'),
    'base_url' => env('HUBSPOT_BASE_URL', 'https://api.hubapi.com'),
    'timeout_seconds' => (int) env('HUBSPOT_TIMEOUT_SECONDS', 30),
    'signed_quotes' => [
        'search_path' => env('HUBSPOT_SIGNED_QUOTES_PATH', '/crm/v3/objects/quotes/search'),
        'sign_status_property' => 'hs_sign_status',
        'sign_status_values' => ['SIGNED', 'MANUALLY_SIGNED'],
        'modified_property' => 'hs_lastmodifieddate',
        'date_properties' => ['hs_last_published_date', 'hs_createdate'],
        'archived_property' => 'hs_archived',
        'sync_status_property' => 'sync_status_odoo',
        'synced_status_values' => ['success', 'already_exists'],
        'lookback_days' => 2,
        'hydrate_associations' => true,
        'association_fallback_properties' => [
            'companies' => [
                'hs_object_id',
                'odoo_id',
            ],
            'contacts' => [
                'hs_object_id',
                'odoo_id',
            ],
            'deals' => [
                'hs_object_id',
                'odoo_id',
            ],
            'line_items' => [
                'hs_object_id',
                'name',
                'quantity',
                'price',
                'hs_sku',
                'hs_product_id',
                'odoo_id',
            ],
        ],
        'properties' => [
            'name',
            'hs_title',
            'hs_status',
            'hs_sign_status',
            'hs_quote_number',
            'hs_object_id',
            'hs_expiration_date',
            'hs_createdate',
            'hs_last_published_date',
            'hs_lastmodifieddate',
            'hubspot_owner_id',
            'odoo_id',
            'sync_status_odoo',
            'last_sync_odoo',
            'last_error_odoo',
            'x_studio_quote_id',
        ],
    ],
    'archived_quotes' => [
        'synced_status_values' => ['success'],
        'properties' => [
            'hs_object_id',
            'hs_quote_number',
            'hs_title',
            'sync_status_odoo',
            'last_sync_odoo',
            'last_error_odoo',
            'odoo_id',
        ],
    ],
    'note_association_type_ids' => [
        'contacts' => (int) env('HUBSPOT_NOTE_ASSOC_CONTACTS', 202),
        'companies' => (int) env('HUBSPOT_NOTE_ASSOC_COMPANIES', 190),
        'deals' => (int) env('HUBSPOT_NOTE_ASSOC_DEALS', 214),
    ],
];
